audit_header: false
title: Raleigh Real Estate Video Blog with Terrence Boykin
description: Our mission at Boykin Realty Associates is to be your best resource for Raleigh real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Boykin Realty Associates, your professional Raleigh Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Terrence Boykin
  title:
  license_number:
  about_markdown: |
    I understand that buying or selling a home is more than just a transaction: it’s a life-changing experience. That’s why I am dedicated to providing exceptional, personalized service to each of my clients. I take great pride in the relationships that I build and will always work relentlessly on my client’s behalf to help them to achieve their real estate goals.

    I work with a team of experts who represent the best and brightest in the industry and we always strive to lead the field in research, innovation, and consumer education. It is essential for today’s buyers and sellers to have a trusted resource who can guide them through the complex world of real estate. With my extensive knowledge and commitment to providing only the best and most timely information to my clients, I am your go-to source for real estate industry insight and advice.
  brand: Boykin Realty Associates
  brokerage: Keller Williams Platinum Realty
  market: Raleigh
  address: 1005 Vandora Springs Rd, Garner, NC 27529
  phone: 919-675-9967
  phone_type:
  phone2:
  phone2_type:
  email: Terrence@RaleighsBestAgent.com
  url: http://raleighsbestagent.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: http://raleighsbestagent.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Raleigh Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Raleigh Home?"
    CTA_text2: "Search the entire MLS for your Raleigh home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://raleighsbestagent.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/RaleighsBestAgent/
  linkedin_url: https://www.linkedin.com/in/terrenceboykin
  youtube_url: https://www.youtube.com/channel/UCvcad_QTJmyzYy4XLOqdZJQ
  twitter_url: https://www.twitter.com/TBoykinRealtor
  instagram_url: https://www.instagram.com/terrence_boykin_realtor/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Raleigh Real Estate Podcast with Terrence Boykin'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Raleigh Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Boykin Realty Associates - your professional Raleigh Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Raleigh, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Terrence Boykin'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Raleigh Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
